### PR TITLE
Bring back and improve text for docket sheet buttons #51.

### PR DESCRIPTION
**Pull request by knod**
The old 'No' button actually had text that was confusing in the context of the new text. Also, the exit icon wasn't appropriate for the 'Yes' button.

Should they just be 'Yes' and 'No' at this point? The question at the bottom seems clear enough. Would it help to add a horizontal line before that last question?

### CODE REVIEW

**Comment by niharikasingh** [comment]
Wasn't there another change in the original PR? To this line https://github.com/knod/docassemble-juvenilesealing/blob/master/docassemble/juvenilesealing/data/questions/petitioner-entrypoint-10.yml#L197 to make it read something like "What's *so special* about certified docket sheets?"

**Comment by knod** [comment]
Yes! Good catch!

**Comment by knod** [comment]
What are your thoughts on simplifying the buttons?

**Comment by niharikasingh** [comment]
> What are your thoughts on simplifying the buttons?

I'm not a UX person so discount what I say appropriately. I think the text you have is good for now. We can change it later once we have more user feedback.

**Pull request merged**
